use std::io::Read;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use serde::Serialize;
use serde_json::Value;

use crate::console::now_unix;
use crate::paths::Layout;
use crate::storage::dir_size;

pub const WORLD_EXT: &str = "vcdbs";
/// SQLite sidecar files that belong to a world file.
const SIDECAR_SUFFIXES: [&str; 2] = ["-shm", "-wal"];

/// Bundled bootstrap definitions, injected only when the manager has to write a
/// `serverconfig.json` before the server has ever run. Vintage Story refuses to
/// boot when `DefaultRoleCode` has no matching `Roles` entry, and the server
/// generates and upgrades the rest of the config on first start. Captured from
/// a 1.22.7 dedicated server.
const DEFAULT_ROLES: &str = include_str!("../assets/default-roles.json");

const MAX_WORLD_NAME: usize = 64;
const MAX_SEED: usize = 64;
const MAX_OVERRIDES: usize = 64;
const PLAY_STYLES: [&str; 5] = [
    "surviveandbuild",
    "exploration",
    "wildernesssurvival",
    "homosapiens",
    "creativebuilding",
];
const WORLD_TYPES: [&str; 2] = ["standard", "superflat"];

/// Wizard input for creating a world before it exists. `world_configuration`
/// entries layer over the playstyle defaults (verified against 1.22.7).
#[derive(Deserialize)]
pub struct WorldSpec {
    pub name: String,
    #[serde(default)]
    pub seed: Option<String>,
    #[serde(default)]
    pub play_style: Option<String>,
    #[serde(default)]
    pub world_type: Option<String>,
    #[serde(default)]
    pub world_configuration: Option<serde_json::Map<String, Value>>,
}

#[derive(Serialize)]
pub struct CreateOutcome {
    pub name: String,
    /// `serverconfig.json` did not exist and a bootstrap one was written.
    pub first_boot: bool,
}

#[derive(Serialize)]
pub struct SaveEntry {
    pub name: String,
    pub size: u64,
    pub modified: u64,
    pub active: bool,
    /// Pre-`vcdbs` world stored as a folder.
    pub legacy: bool,
    /// Configured in `serverconfig.json` but not yet generated by the server.
    pub pending: bool,
}

pub fn saves_dir(layout: &Layout) -> PathBuf {
    layout.server_dir().join("Saves")
}

fn serverconfig_path(layout: &Layout) -> PathBuf {
    layout.server_dir().join("serverconfig.json")
}

/// Validate a world name: a plain file/folder name inside `Saves`.
fn validate_name(name: &str) -> Result<&str, String> {
    let trimmed = name.trim();
    if trimmed.is_empty()
        || trimmed.contains('/')
        || trimmed.contains('\\')
        || trimmed.contains("..")
        || trimmed.starts_with('.')
    {
        return Err("invalid world name".into());
    }
    Ok(trimmed)
}

/// Validates a world name and its length (shared by create/duplicate/rename).
fn validate_world_name(name: &str) -> Result<&str, String> {
    let name = validate_name(name)?;
    if name.chars().count() > MAX_WORLD_NAME {
        return Err(format!(
            "world name is too long (max {MAX_WORLD_NAME} characters)"
        ));
    }
    Ok(name)
}

/// Refuses names that are taken on disk or already configured as the target.
fn ensure_name_available(layout: &Layout, name: &str) -> Result<(), String> {
    let saves = saves_dir(layout);
    if saves.join(format!("{name}.{WORLD_EXT}")).exists() || saves.join(name).exists() {
        return Err(format!("a world named {name} already exists"));
    }
    if active_world(layout)
        .as_deref()
        .is_some_and(|active| active.eq_ignore_ascii_case(name))
    {
        return Err(format!("a world named {name} is already configured"));
    }
    Ok(())
}

/// Path of a world: `<name>.vcdbs` (modern) or the legacy `<name>/` folder.
pub fn world_path(layout: &Layout, name: &str) -> Result<PathBuf, String> {
    let name = validate_name(name)?;
    let modern = saves_dir(layout).join(format!("{name}.{WORLD_EXT}"));
    if modern.is_file() {
        return Ok(modern);
    }
    let legacy = saves_dir(layout).join(name);
    if legacy.is_dir() {
        return Ok(legacy);
    }
    Err(format!("{name} is not a world"))
}

/// The world the server will load, from `serverconfig.json > WorldConfig`:
/// `SaveFileLocation` stem first, then `WorldName`.
pub fn active_world(layout: &Layout) -> Option<String> {
    let config = world_config_object(layout)?;
    if let Some(location) = config.get("SaveFileLocation").and_then(Value::as_str) {
        let stem = Path::new(location.trim())
            .file_stem()
            .map(|stem| stem.to_string_lossy().into_owned())
            .unwrap_or_default();
        if !stem.is_empty() {
            return Some(stem);
        }
    }
    config
        .get("WorldName")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .map(str::to_string)
}

/// `serverconfig.json > WorldConfig` as an object, when present.
fn world_config_object(layout: &Layout) -> Option<serde_json::Map<String, Value>> {
    let raw = std::fs::read_to_string(serverconfig_path(layout)).ok()?;
    let value: Value = serde_json::from_str(&raw).ok()?;
    value.get("WorldConfig")?.as_object().cloned()
}

pub fn list_saves(layout: &Layout) -> Vec<SaveEntry> {
    let Ok(entries) = std::fs::read_dir(saves_dir(layout)) else {
        return Vec::new();
    };
    let active = active_world(layout);
    let mut saves: Vec<SaveEntry> = Vec::new();

    for entry in entries.flatten() {
        let path = entry.path();
        let file_name = entry.file_name().to_string_lossy().into_owned();
        if file_name.starts_with('.') {
            continue;
        }
        let (name, legacy, size) = if path.is_file() {
            if !file_name.to_lowercase().ends_with(&format!(".{WORLD_EXT}")) {
                continue;
            }
            let stem = path
                .file_stem()
                .map(|stem| stem.to_string_lossy().into_owned())
                .unwrap_or_default();
            (stem, false, file_size_with_sidecars(&path))
        } else if path.is_dir() {
            (file_name, true, dir_size(&path))
        } else {
            continue;
        };
        if name.is_empty() {
            continue;
        }
        saves.push(SaveEntry {
            name,
            size,
            modified: modified_time(&path),
            active: false,
            legacy,
            pending: false,
        });
    }

    if let Some(active) = active.as_deref() {
        for save in saves.iter_mut() {
            save.active = save.name.eq_ignore_ascii_case(active);
        }
        // A configured world that has not been generated yet (created through
        // the wizard, materialized on the next server start).
        if !saves.iter().any(|save| save.active) {
            saves.push(SaveEntry {
                name: active.to_string(),
                size: 0,
                modified: 0,
                active: true,
                legacy: false,
                pending: true,
            });
        }
    }
    // With a single world and no configured target the server loads it.
    if active.is_none() && saves.len() == 1 {
        if let Some(save) = saves.first_mut() {
            save.active = true;
        }
    }
    saves.sort_by(|a, b| b.modified.cmp(&a.modified));
    saves
}

fn file_size_with_sidecars(path: &Path) -> u64 {
    let mut size = path.metadata().map(|meta| meta.len()).unwrap_or(0);
    for suffix in SIDECAR_SUFFIXES {
        let sidecar = sidecar_path(path, suffix);
        size += sidecar
            .metadata()
            .map(|meta| meta.len())
            .unwrap_or_default();
    }
    size
}

fn sidecar_path(path: &Path, suffix: &str) -> PathBuf {
    let mut sidecar = path.as_os_str().to_os_string();
    sidecar.push(suffix);
    PathBuf::from(sidecar)
}

fn modified_time(path: &Path) -> u64 {
    path.metadata()
        .and_then(|meta| meta.modified())
        .ok()
        .and_then(|time| time.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

/// Points `serverconfig.json > WorldConfig.SaveFileLocation` at this world
/// (takes effect on next start).
pub fn activate(layout: &Layout, name: &str) -> Result<(), String> {
    let world = world_path(layout, name)?;
    let file_name = world
        .file_name()
        .map(|part| part.to_string_lossy().into_owned())
        .unwrap_or_default();
    let location = format!("Saves/{file_name}");

    let path = serverconfig_path(layout);
    let content = std::fs::read_to_string(&path)
        .map_err(|e| format!("serverconfig.json is not readable: {e}"))?;
    let mut value: Value = serde_json::from_str(&content)
        .map_err(|e| format!("serverconfig.json is not valid JSON: {e}"))?;
    let root = value
        .as_object_mut()
        .ok_or("serverconfig.json is not an object")?;
    let world_config = root
        .entry("WorldConfig")
        .or_insert_with(|| Value::Object(Default::default()));
    let world_config = world_config
        .as_object_mut()
        .ok_or("serverconfig.json WorldConfig is not an object")?;
    world_config.insert("SaveFileLocation".into(), Value::String(location));

    let pretty = serde_json::to_string_pretty(&value).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, pretty).map_err(|e| format!("write failed: {e}"))?;
    std::fs::rename(&tmp, &path).map_err(|e| format!("replace failed: {e}"))
}

pub fn delete_save(layout: &Layout, name: &str) -> Result<(), String> {
    let path = world_path(layout, name)?;
    if path.is_dir() {
        return std::fs::remove_dir_all(&path).map_err(|e| format!("cannot delete {name}: {e}"));
    }
    std::fs::remove_file(&path).map_err(|e| format!("cannot delete {name}: {e}"))?;
    for suffix in SIDECAR_SUFFIXES {
        let _ = std::fs::remove_file(sidecar_path(&path, suffix));
    }
    Ok(())
}

/// World settings live in `serverconfig.json > WorldConfig`. Returns the pretty
/// JSON of that object plus a flag when serverconfig.json does not exist yet.
pub fn read_world_config(layout: &Layout, _name: &str) -> Result<(String, bool), String> {
    let path = serverconfig_path(layout);
    if !path.exists() {
        return Ok(("{}".into(), true));
    }
    let raw = std::fs::read_to_string(&path)
        .map_err(|e| format!("serverconfig.json is not readable: {e}"))?;
    let value: Value = serde_json::from_str(&raw)
        .map_err(|e| format!("serverconfig.json is not valid JSON: {e}"))?;
    let world_config = value
        .get("WorldConfig")
        .cloned()
        .unwrap_or_else(|| Value::Object(Default::default()));
    let pretty = serde_json::to_string_pretty(&world_config).map_err(|e| e.to_string())?;
    Ok((pretty, false))
}

pub fn write_world_config(layout: &Layout, _name: &str, content: &str) -> Result<(), String> {
    let parsed: Value =
        json5::from_str(content).map_err(|e| format!("Refusing to save invalid JSON5: {e}"))?;
    if !parsed.is_object() {
        return Err("world config must be a JSON object".into());
    }
    let path = serverconfig_path(layout);
    let raw = std::fs::read_to_string(&path).map_err(|e| {
        format!("serverconfig.json is not readable ({e}) — it is generated on first server start")
    })?;
    let mut value: Value = serde_json::from_str(&raw)
        .map_err(|e| format!("serverconfig.json is not valid JSON: {e}"))?;
    let root = value
        .as_object_mut()
        .ok_or("serverconfig.json is not an object")?;
    root.insert("WorldConfig".into(), parsed);
    let pretty = serde_json::to_string_pretty(&value).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, pretty).map_err(|e| format!("write failed: {e}"))?;
    std::fs::rename(&tmp, &path).map_err(|e| format!("replace failed: {e}"))
}

/// Creates a new world by pointing `serverconfig.json > WorldConfig` at a save
/// file that does not exist yet; the server generates it on the next start.
/// Writes a bootstrap `serverconfig.json` when the server has never run — the
/// wizard fills the gap between install and the engine's first start.
pub fn create_world(layout: &Layout, spec: &WorldSpec) -> Result<CreateOutcome, String> {
    let name = validate_world_name(&spec.name)?;
    ensure_name_available(layout, name)?;
    let saves = saves_dir(layout);
    let seed = match spec.seed.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
        Some(seed) if seed.chars().count() > MAX_SEED => {
            return Err(format!("seed is too long (max {MAX_SEED} characters)"));
        }
        Some(seed) => Some(seed.to_string()),
        None => None,
    };
    if let Some(style) = spec.play_style.as_deref() {
        if !PLAY_STYLES.contains(&style) {
            return Err(format!("unknown playstyle: {style}"));
        }
    }
    if let Some(world_type) = spec.world_type.as_deref() {
        if !WORLD_TYPES.contains(&world_type) {
            return Err(format!("unknown world type: {world_type}"));
        }
    }
    if let Some(overrides) = &spec.world_configuration {
        validate_overrides(overrides)?;
    }

    std::fs::create_dir_all(&saves).map_err(|e| format!("cannot create Saves dir: {e}"))?;

    let path = serverconfig_path(layout);
    let first_boot = !path.exists();
    let mut root = if first_boot {
        bootstrap_defaults()?
    } else {
        read_serverconfig(&path)?
    };

    // The server refuses to boot when the default role is missing; repair a
    // hand-edited config that lost its roles.
    if !has_roles(&root) {
        let template = bootstrap_defaults()?;
        for key in ["Roles", "DefaultRoleCode", "ConfigVersion"] {
            root.entry(key.to_string())
                .or_insert_with(|| template[key].clone());
        }
    }

    let save_location = saves.join(format!("{name}.{WORLD_EXT}"));
    let world_config = root
        .entry("WorldConfig")
        .or_insert_with(|| Value::Object(Default::default()))
        .as_object_mut()
        .ok_or("serverconfig.json WorldConfig is not an object")?;
    world_config.insert("WorldName".into(), Value::String(name.to_string()));
    world_config.insert(
        "SaveFileLocation".into(),
        Value::String(save_location.to_string_lossy().into_owned()),
    );
    world_config.insert(
        "Seed".into(),
        seed.map(Value::String).unwrap_or(Value::Null),
    );
    if let Some(style) = spec.play_style.as_deref() {
        world_config.insert("PlayStyle".into(), Value::String(style.into()));
        world_config.insert(
            "PlayStyleLangCode".into(),
            Value::String(play_style_lang_code(style).into()),
        );
    }
    if let Some(world_type) = spec.world_type.as_deref() {
        world_config.insert("WorldType".into(), Value::String(world_type.into()));
    }
    world_config.insert(
        "WorldConfiguration".into(),
        spec.world_configuration
            .clone()
            .map(Value::Object)
            .unwrap_or(Value::Null),
    );

    write_json_atomic(&path, &Value::Object(root))?;
    Ok(CreateOutcome {
        name: name.to_string(),
        first_boot,
    })
}

/// Copies a world (file plus sidecars, or a legacy folder) under a new name.
/// The copy is independent; serverconfig is not touched.
pub fn duplicate_save(layout: &Layout, name: &str, new_name: &str) -> Result<String, String> {
    let source = world_path(layout, name)?;
    let new = validate_world_name(new_name)?;
    ensure_name_available(layout, new)?;
    let saves = saves_dir(layout);
    std::fs::create_dir_all(&saves).map_err(|e| format!("cannot create Saves dir: {e}"))?;

    if source.is_dir() {
        copy_dir(&source, &saves.join(new))?;
    } else {
        let target = saves.join(format!("{new}.{WORLD_EXT}"));
        std::fs::copy(&source, &target).map_err(|e| format!("cannot copy world: {e}"))?;
        for suffix in SIDECAR_SUFFIXES {
            let sidecar = sidecar_path(&source, suffix);
            if sidecar.is_file() {
                std::fs::copy(&sidecar, sidecar_path(&target, suffix))
                    .map_err(|e| format!("cannot copy world sidecar: {e}"))?;
            }
        }
    }
    Ok(new.to_string())
}

/// Renames a world on disk; when it was the configured world, serverconfig is
/// repointed. Returns whether it was the active world.
pub fn rename_save(layout: &Layout, name: &str, new_name: &str) -> Result<bool, String> {
    let source = world_path(layout, name)?;
    let new = validate_world_name(new_name)?;
    if new.eq_ignore_ascii_case(name) {
        return Err("the new name is the same as the current name".into());
    }
    ensure_name_available(layout, new)?;
    let was_active = active_world(layout)
        .as_deref()
        .is_some_and(|active| active.eq_ignore_ascii_case(name));

    let target = if source.is_dir() {
        saves_dir(layout).join(new)
    } else {
        saves_dir(layout).join(format!("{new}.{WORLD_EXT}"))
    };
    std::fs::rename(&source, &target).map_err(|e| format!("cannot rename world: {e}"))?;
    if !source.is_dir() {
        for suffix in SIDECAR_SUFFIXES {
            let sidecar = sidecar_path(&source, suffix);
            if sidecar.is_file() {
                let _ = std::fs::rename(&sidecar, sidecar_path(&target, suffix));
            }
        }
    }

    if was_active {
        let path = serverconfig_path(layout);
        let mut root = read_serverconfig(&path)?;
        let location = format!(
            "Saves/{}",
            target
                .file_name()
                .map(|part| part.to_string_lossy().into_owned())
                .unwrap_or_default()
        );
        let world_config = root
            .entry("WorldConfig")
            .or_insert_with(|| Value::Object(Default::default()))
            .as_object_mut()
            .ok_or("serverconfig.json WorldConfig is not an object")?;
        world_config.insert("SaveFileLocation".into(), Value::String(location));
        world_config.insert("WorldName".into(), Value::String(new.to_string()));
        write_json_atomic(&path, &Value::Object(root))?;
    }
    Ok(was_active)
}

fn copy_dir(source: &Path, target: &Path) -> Result<(), String> {
    std::fs::create_dir_all(target)
        .map_err(|e| format!("cannot create {}: {e}", target.display()))?;
    let entries =
        std::fs::read_dir(source).map_err(|e| format!("cannot read {}: {e}", source.display()))?;
    for entry in entries.flatten() {
        let path = entry.path();
        let out = target.join(entry.file_name());
        if path.is_dir() {
            copy_dir(&path, &out)?;
        } else if path.is_file() {
            std::fs::copy(&path, &out).map_err(|e| format!("cannot copy {}: {e}", path.display()))?;
        }
    }
    Ok(())
}

fn play_style_lang_code(style: &str) -> &'static str {
    match style {
        "exploration" => "preset-exploration",
        "wildernesssurvival" => "preset-wildernesssurvival",
        "homosapiens" => "preset-homosapiens",
        "creativebuilding" => "creativebuilding",
        _ => "surviveandbuild-bands",
    }
}

fn validate_overrides(overrides: &serde_json::Map<String, Value>) -> Result<(), String> {
    if overrides.len() > MAX_OVERRIDES {
        return Err("too many world generation overrides".into());
    }
    for (key, value) in overrides {
        let valid_key = !key.is_empty()
            && key.len() <= 64
            && key.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
            && key.chars().all(|c| c.is_ascii_alphanumeric());
        if !valid_key {
            return Err(format!("invalid world generation key: {key}"));
        }
        let valid_value = match value {
            Value::String(text) => text.chars().count() <= 256,
            Value::Bool(_) | Value::Number(_) => true,
            _ => false,
        };
        if !valid_value {
            return Err(format!("invalid world generation value for {key}"));
        }
    }
    Ok(())
}

fn has_roles(root: &serde_json::Map<String, Value>) -> bool {
    root.get("Roles")
        .and_then(Value::as_array)
        .is_some_and(|roles| !roles.is_empty())
}

fn bootstrap_defaults() -> Result<serde_json::Map<String, Value>, String> {
    serde_json::from_str::<Value>(DEFAULT_ROLES)
        .map_err(|e| format!("bundled default roles are invalid: {e}"))?
        .as_object()
        .cloned()
        .ok_or_else(|| "bundled default roles are not an object".into())
}

fn read_serverconfig(path: &Path) -> Result<serde_json::Map<String, Value>, String> {
    let raw = std::fs::read_to_string(path)
        .map_err(|e| format!("serverconfig.json is not readable: {e}"))?;
    serde_json::from_str::<Value>(&raw)
        .map_err(|e| format!("serverconfig.json is not valid JSON: {e}"))?
        .as_object()
        .cloned()
        .ok_or_else(|| "serverconfig.json is not an object".into())
}

/// Atomically replaces `path` with pretty-printed JSON.
fn write_json_atomic(path: &Path, value: &Value) -> Result<(), String> {
    let pretty = serde_json::to_string_pretty(value).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, pretty).map_err(|e| format!("write failed: {e}"))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("replace failed: {e}"))
}

/// Zips a world into `config/exports` and returns (path, download filename).
pub fn zip_save(layout: &Layout, name: &str) -> Result<(PathBuf, String), String> {
    let world = world_path(layout, name)?;
    let exports = layout.config_dir().join("exports");
    std::fs::create_dir_all(&exports).map_err(|e| format!("cannot create exports dir: {e}"))?;
    let filename = format!("{name}-{}.zip", now_unix());
    let zip_path = exports.join(&filename);
    let file =
        std::fs::File::create(&zip_path).map_err(|e| format!("cannot create archive: {e}"))?;
    let mut zip = zip::ZipWriter::new(file);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);

    if world.is_dir() {
        add_dir(&mut zip, &world, Path::new(""), &options)?;
    } else {
        add_file(&mut zip, &world, &options)?;
        for suffix in SIDECAR_SUFFIXES {
            let sidecar = sidecar_path(&world, suffix);
            if sidecar.is_file() {
                add_file(&mut zip, &sidecar, &options)?;
            }
        }
    }
    zip.finish()
        .map_err(|e| format!("cannot finish archive: {e}"))?;
    Ok((zip_path, filename))
}

/// Imports an uploaded world. `.vcdbs` files are copied in directly; zip
/// archives are searched for a `.vcdbs` member (legacy world folders work
/// too). Returns the final world name.
pub fn import_world(layout: &Layout, source: &Path, original_name: &str) -> Result<String, String> {
    let lower = original_name.to_lowercase();
    if lower.ends_with(&format!(".{WORLD_EXT}")) {
        let stem = original_name
            .trim_end_matches(&format!(".{WORLD_EXT}"))
            .trim_end_matches(&format!(".{}", WORLD_EXT.to_uppercase()));
        return import_vcdbs(layout, source, stem);
    }
    if !lower.ends_with(".zip") {
        return Err("upload a .vcdbs world file or a .zip archive".into());
    }

    let dir = saves_dir(layout);
    std::fs::create_dir_all(&dir).map_err(|e| format!("cannot create Saves dir: {e}"))?;
    let staging = dir.join(format!(".upload-{}", now_unix()));
    if staging.exists() {
        let _ = std::fs::remove_dir_all(&staging);
    }
    std::fs::create_dir_all(&staging).map_err(|e| format!("cannot create staging dir: {e}"))?;

    let result = (|| -> Result<String, String> {
        let file = std::fs::File::open(source).map_err(|e| format!("cannot open zip: {e}"))?;
        let mut archive =
            zip::ZipArchive::new(file).map_err(|e| format!("invalid zip archive: {e}"))?;
        for index in 0..archive.len() {
            let mut entry = archive
                .by_index(index)
                .map_err(|e| format!("zip entry error: {e}"))?;
            // `enclosed_name` rejects traversal (../, absolute paths).
            let Some(relative) = entry.enclosed_name() else {
                continue;
            };
            let out = staging.join(relative);
            if entry.is_dir() {
                std::fs::create_dir_all(&out).map_err(|e| format!("cannot create dir: {e}"))?;
                continue;
            }
            if let Some(parent) = out.parent() {
                std::fs::create_dir_all(parent).map_err(|e| format!("cannot create dir: {e}"))?;
            }
            let mut target =
                std::fs::File::create(&out).map_err(|e| format!("cannot write file: {e}"))?;
            std::io::copy(&mut entry, &mut target).map_err(|e| format!("cannot copy file: {e}"))?;
        }

        // Prefer a modern `.vcdbs` world file anywhere in the archive.
        if let Some(vcdbs) = find_vcdbs(&staging) {
            let stem = vcdbs
                .file_stem()
                .map(|stem| stem.to_string_lossy().into_owned())
                .unwrap_or_default();
            let name = import_vcdbs(layout, &vcdbs, &stem)?;
            return Ok(name);
        }

        // Legacy folder-style world: a single top-level directory.
        let roots: Vec<PathBuf> = std::fs::read_dir(&staging)
            .map_err(|e| format!("cannot read staging dir: {e}"))?
            .flatten()
            .map(|entry| entry.path())
            .collect();
        let (root, name) = if roots.len() == 1 && roots[0].is_dir() {
            let name = roots[0]
                .file_name()
                .map(|part| part.to_string_lossy().into_owned())
                .unwrap_or_default();
            (roots[0].clone(), name)
        } else {
            (staging.clone(), sanitize_name(original_name))
        };
        if name.is_empty() {
            return Err("cannot determine a world name from the archive".into());
        }
        if dir_size(&root) == 0 {
            return Err("the archive contains no files".into());
        }
        let target = dir.join(&name);
        if target.exists() {
            return Err(format!("a world named {name} already exists"));
        }
        std::fs::rename(&root, &target).map_err(|e| format!("cannot move world into place: {e}"))?;
        Ok(name)
    })();

    if staging.exists() {
        let _ = std::fs::remove_dir_all(&staging);
    }
    result
}

fn find_vcdbs(dir: &Path) -> Option<PathBuf> {
    let entries = std::fs::read_dir(dir).ok()?;
    let mut subdirs = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            subdirs.push(path);
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_lowercase();
        if name.ends_with(&format!(".{WORLD_EXT}")) {
            return Some(path);
        }
    }
    subdirs.into_iter().find_map(|dir| find_vcdbs(&dir))
}

fn import_vcdbs(layout: &Layout, source: &Path, raw_name: &str) -> Result<String, String> {
    let name = sanitize_name(raw_name);
    if name.is_empty() {
        return Err("cannot determine a world name".into());
    }
    let dir = saves_dir(layout);
    std::fs::create_dir_all(&dir).map_err(|e| format!("cannot create Saves dir: {e}"))?;
    let target = dir.join(format!("{name}.{WORLD_EXT}"));
    if target.exists() {
        return Err(format!("a world named {name} already exists"));
    }
    std::fs::rename(source, &target).or_else(|_| {
        std::fs::copy(source, &target).map(|_| ()).and_then(|_| {
            std::fs::remove_file(source).or(Ok(()))
        })
    })
    .map_err(|e| format!("cannot move world into place: {e}"))?;
    Ok(name)
}

fn sanitize_name(input: &str) -> String {
    let base = input
        .trim()
        .trim_end_matches(&format!(".{WORLD_EXT}"))
        .trim_end_matches(&format!(".{}", WORLD_EXT.to_uppercase()))
        .trim_end_matches(".zip")
        .trim_end_matches(".ZIP");
    let cleaned: String = base
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | ' ') {
                c
            } else {
                '_'
            }
        })
        .collect();
    let trimmed = cleaned.trim().to_string();
    if trimmed.is_empty() {
        "imported".into()
    } else {
        trimmed.chars().take(64).collect()
    }
}

fn add_file(
    zip: &mut zip::ZipWriter<std::fs::File>,
    path: &Path,
    options: &zip::write::SimpleFileOptions,
) -> Result<(), String> {
    let name = path
        .file_name()
        .map(|part| part.to_string_lossy().into_owned())
        .unwrap_or_default();
    zip.start_file(name, *options)
        .map_err(|e| format!("cannot add to archive: {e}"))?;
    let mut source = std::fs::File::open(path).map_err(|e| format!("cannot open file: {e}"))?;
    let mut buffer = Vec::new();
    source
        .read_to_end(&mut buffer)
        .map_err(|e| format!("cannot read file: {e}"))?;
    std::io::Write::write_all(zip, &buffer).map_err(|e| format!("cannot write entry: {e}"))?;
    Ok(())
}

fn add_dir(
    zip: &mut zip::ZipWriter<std::fs::File>,
    dir: &Path,
    prefix: &Path,
    options: &zip::write::SimpleFileOptions,
) -> Result<(), String> {
    let entries =
        std::fs::read_dir(dir).map_err(|e| format!("cannot read {}: {e}", dir.display()))?;
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let relative = prefix.join(&name);
        if path.is_dir() {
            add_dir(zip, &path, &relative, options)?;
        } else if path.is_file() {
            let relative_name = relative.to_string_lossy().replace('\\', "/");
            zip.start_file(relative_name, *options)
                .map_err(|e| format!("cannot add to archive: {e}"))?;
            let mut source =
                std::fs::File::open(&path).map_err(|e| format!("cannot open file: {e}"))?;
            let mut buffer = Vec::new();
            source
                .read_to_end(&mut buffer)
                .map_err(|e| format!("cannot read file: {e}"))?;
            std::io::Write::write_all(zip, &buffer)
                .map_err(|e| format!("cannot write entry: {e}"))?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_unsafe_world_names() {
        let layout = Layout::new(std::env::temp_dir());
        assert!(world_path(&layout, "../evil").is_err());
        assert!(world_path(&layout, "a/b").is_err());
        assert!(world_path(&layout, "").is_err());
        assert!(world_path(&layout, ".hidden").is_err());
        assert!(world_path(&layout, "Ember Hollow").is_err()); // nothing installed
    }

    #[test]
    fn lists_vcdbs_files_and_reads_active_world() {
        let dir = std::env::temp_dir().join(format!("vs-webui-saves-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let layout = Layout::new(&dir);
        std::fs::create_dir_all(saves_dir(&layout)).unwrap();
        std::fs::write(saves_dir(&layout).join("Ember Hollow.vcdbs"), vec![0u8; 64]).unwrap();
        std::fs::write(saves_dir(&layout).join("Ember Hollow.vcdbs-wal"), vec![0u8; 8]).unwrap();
        std::fs::write(saves_dir(&layout).join("Old World.vcdbs"), vec![0u8; 32]).unwrap();
        std::fs::write(
            serverconfig_path(&layout),
            serde_json::json!({
                "WorldConfig": { "SaveFileLocation": "Saves/Old World.vcdbs", "WorldName": "Ignored" }
            })
            .to_string(),
        )
        .unwrap();

        let saves = list_saves(&layout);
        assert_eq!(saves.len(), 2);
        let active = saves.iter().find(|save| save.active).unwrap();
        assert_eq!(active.name, "Old World");
        let ember = saves.iter().find(|save| save.name == "Ember Hollow").unwrap();
        assert_eq!(ember.size, 72); // world file + sidecar
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn sanitizes_uploaded_fallback_names() {
        assert_eq!(sanitize_name("My World.zip"), "My World");
        assert_eq!(sanitize_name("default.vcdbs"), "default");
        assert_eq!(sanitize_name(""), "imported");
    }

    fn test_layout(tag: &str) -> Layout {
        let dir = std::env::temp_dir().join(format!(
            "vs-webui-worlds-{tag}-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        Layout::new(&dir)
    }

    fn spec(name: &str) -> WorldSpec {
        WorldSpec {
            name: name.into(),
            seed: None,
            play_style: None,
            world_type: None,
            world_configuration: None,
        }
    }

    #[test]
    fn create_world_bootstraps_serverconfig() {
        let layout = test_layout("bootstrap");
        let mut world = spec("Ember Hollow");
        world.seed = Some("  embers-2026  ".into());
        world.play_style = Some("exploration".into());
        world.world_type = Some("superflat".into());
        world.world_configuration = Some(
            serde_json::json!({ "startingClimate": "arctic", "daysPerMonth": "12" })
                .as_object()
                .unwrap()
                .clone(),
        );

        let outcome = create_world(&layout, &world).unwrap();
        assert_eq!(outcome.name, "Ember Hollow");
        assert!(outcome.first_boot);

        let config: Value =
            serde_json::from_str(&std::fs::read_to_string(serverconfig_path(&layout)).unwrap())
                .unwrap();
        assert!(!config["Roles"].as_array().unwrap().is_empty());
        assert_eq!(config["DefaultRoleCode"], "suplayer");
        let wc = &config["WorldConfig"];
        assert_eq!(wc["WorldName"], "Ember Hollow");
        assert_eq!(wc["Seed"], "embers-2026"); // trimmed
        assert_eq!(wc["PlayStyle"], "exploration");
        assert_eq!(wc["PlayStyleLangCode"], "preset-exploration");
        assert_eq!(wc["WorldType"], "superflat");
        assert_eq!(wc["WorldConfiguration"]["startingClimate"], "arctic");
        let location = wc["SaveFileLocation"].as_str().unwrap();
        assert!(location.ends_with("Saves/Ember Hollow.vcdbs"));
        assert!(Path::new(location).is_absolute());
        let _ = std::fs::remove_dir_all(layout.root);
    }

    #[test]
    fn create_world_preserves_existing_serverconfig() {
        let layout = test_layout("preserve");
        let saves = saves_dir(&layout);
        std::fs::create_dir_all(&saves).unwrap();
        std::fs::write(saves.join("old.vcdbs"), vec![0u8; 8]).unwrap();
        std::fs::write(
            serverconfig_path(&layout),
            serde_json::json!({
                "ServerName": "My Server",
                "Roles": bootstrap_defaults().unwrap().get("Roles").unwrap().clone(),
                "DefaultRoleCode": "suplayer",
                "WorldConfig": {
                    "WorldName": "old",
                    "SaveFileLocation": "Saves/old.vcdbs",
                    "DisabledMods": ["some-mod"]
                }
            })
            .to_string(),
        )
        .unwrap();

        let outcome = create_world(&layout, &spec("New Home")).unwrap();
        assert!(!outcome.first_boot);
        let config: Value =
            serde_json::from_str(&std::fs::read_to_string(serverconfig_path(&layout)).unwrap())
                .unwrap();
        assert_eq!(config["ServerName"], "My Server");
        assert_eq!(config["WorldConfig"]["WorldName"], "New Home");
        assert_eq!(config["WorldConfig"]["DisabledMods"][0], "some-mod");
        assert_eq!(config["WorldConfig"]["Seed"], Value::Null);
        assert_eq!(config["WorldConfig"]["WorldConfiguration"], Value::Null);
        let _ = std::fs::remove_dir_all(layout.root);
    }

    #[test]
    fn create_world_repairs_missing_roles() {
        let layout = test_layout("repair");
        std::fs::create_dir_all(serverconfig_path(&layout).parent().unwrap()).unwrap();
        std::fs::write(
            serverconfig_path(&layout),
            serde_json::json!({ "ServerName": "Broken", "WorldConfig": {} }).to_string(),
        )
        .unwrap();
        create_world(&layout, &spec("Fixed")).unwrap();
        let config: Value =
            serde_json::from_str(&std::fs::read_to_string(serverconfig_path(&layout)).unwrap())
                .unwrap();
        assert_eq!(config["ServerName"], "Broken");
        assert!(!config["Roles"].as_array().unwrap().is_empty());
        assert_eq!(config["DefaultRoleCode"], "suplayer");
    }

    #[test]
    fn create_world_shows_pending_entry_and_blocks_duplicates() {
        let layout = test_layout("pending");
        create_world(&layout, &spec("Fresh Start")).unwrap();

        let saves = list_saves(&layout);
        assert_eq!(saves.len(), 1);
        assert_eq!(saves[0].name, "Fresh Start");
        assert!(saves[0].pending);
        assert!(saves[0].active);

        // The pending world cannot be created (or configured) again.
        assert!(create_world(&layout, &spec("Fresh Start")).is_err());
        assert!(create_world(&layout, &spec("fresh start")).is_err());

        // Once the server has generated the file the entry stops being pending.
        std::fs::write(saves_dir(&layout).join("Fresh Start.vcdbs"), vec![0u8; 16]).unwrap();
        let saves = list_saves(&layout);
        assert_eq!(saves.len(), 1);
        assert!(!saves[0].pending);
        assert!(saves[0].active);
        let _ = std::fs::remove_dir_all(layout.root);
    }

    #[test]
    fn duplicates_and_renames_worlds() {
        let layout = test_layout("dupe");
        let saves = saves_dir(&layout);
        std::fs::create_dir_all(&saves).unwrap();
        std::fs::write(saves.join("Home.vcdbs"), vec![1u8; 32]).unwrap();
        std::fs::write(saves.join("Home.vcdbs-wal"), vec![2u8; 8]).unwrap();
        std::fs::write(
            serverconfig_path(&layout),
            serde_json::json!({
                "WorldConfig": { "WorldName": "Home", "SaveFileLocation": "Saves/Home.vcdbs" }
            })
            .to_string(),
        )
        .unwrap();

        // Duplicate copies file + sidecar and refuses collisions.
        assert_eq!(
            duplicate_save(&layout, "Home", "Home Copy").unwrap(),
            "Home Copy"
        );
        assert!(saves.join("Home Copy.vcdbs").exists());
        assert!(saves.join("Home Copy.vcdbs-wal").exists());
        assert!(duplicate_save(&layout, "Home", "Home Copy").is_err());

        // Renaming the active world repoints serverconfig.
        assert!(rename_save(&layout, "Home", "Home Renamed").unwrap());
        assert!(!saves.join("Home.vcdbs").exists());
        assert!(saves.join("Home Renamed.vcdbs").exists());
        assert!(saves.join("Home Renamed.vcdbs-wal").exists());
        let config: Value = serde_json::from_str(
            &std::fs::read_to_string(serverconfig_path(&layout)).unwrap(),
        )
        .unwrap();
        let location = config["WorldConfig"]["SaveFileLocation"].as_str().unwrap();
        assert!(location.ends_with("Home Renamed.vcdbs"));
        assert_eq!(config["WorldConfig"]["WorldName"], "Home Renamed");

        // Renaming a non-active world leaves serverconfig alone.
        let before = std::fs::read_to_string(serverconfig_path(&layout)).unwrap();
        assert!(!rename_save(&layout, "Home Copy", "Copy 2").unwrap());
        assert_eq!(
            std::fs::read_to_string(serverconfig_path(&layout)).unwrap(),
            before
        );

        // Collisions and no-op renames are refused.
        assert!(rename_save(&layout, "Copy 2", "Home Renamed").is_err());
        assert!(rename_save(&layout, "Copy 2", "Copy 2").is_err());
        assert!(duplicate_save(&layout, "Copy 2", "Home Renamed").is_err());
        let _ = std::fs::remove_dir_all(layout.root);
    }

    #[test]
    fn create_world_rejects_conflicts_and_invalid_input() {
        let layout = test_layout("reject");
        let saves = saves_dir(&layout);
        std::fs::create_dir_all(&saves).unwrap();
        std::fs::write(saves.join("Taken.vcdbs"), vec![0u8; 4]).unwrap();

        assert!(create_world(&layout, &spec("Taken")).is_err());
        assert!(create_world(&layout, &spec("../evil")).is_err());
        assert!(create_world(&layout, &spec(&"x".repeat(65))).is_err());

        let mut world = spec("Seedling");
        world.seed = Some("y".repeat(65));
        assert!(create_world(&layout, &world).is_err());

        let mut world = spec("Seedling");
        world.play_style = Some("nonsense".into());
        assert!(create_world(&layout, &world).is_err());

        let mut world = spec("Seedling");
        world.world_type = Some("round".into());
        assert!(create_world(&layout, &world).is_err());

        let mut world = spec("Seedling");
        world.world_configuration = Some(
            serde_json::json!({ "bad key!": "x" })
                .as_object()
                .unwrap()
                .clone(),
        );
        assert!(create_world(&layout, &world).is_err());
        // Nothing was written for the rejected specs.
        assert!(!serverconfig_path(&layout).exists());
    }
}
